CREATE DATABASE SINHVIENKT

USE SINHVIENKT
CREATE TABLE LOP
(
	MALOP CHAR(3) NOT NULL PRIMARY KEY,
	TENLOP NVARCHAR(30) NOT NULL
);
CREATE TABLE SINHVIEN
(
	MASV CHAR(6) NOT NULL PRIMARY KEY,
	HOTENSV NVARCHAR(40) NOT NULL,
	NGAYSINH DATETIME,
	MALOP CHAR(3) FOREIGN KEY REFERENCES LOP(MALOP)
);
INSERT INTO LOP(MALOP,TENLOP)
VALUES ('1','21DTHE4')
INSERT INTO LOP(MALOP,TENLOP)
VALUES ('2','21DTHE6')
INSERT INTO SINHVIEN(MASV,HOTENSV,NGAYSINH,MALOP)
VALUES ('1','TUONG','2003-10-26','1')
INSERT INTO SINHVIEN(MASV,HOTENSV,NGAYSINH,MALOP)
VALUES ('2','TRUYEN','2003-02-16','2')
INSERT INTO SINHVIEN(MASV,HOTENSV,NGAYSINH,MALOP)
VALUES ('3','LUAN','2003-08-26','1')
INSERT INTO SINHVIEN(MASV,HOTENSV,NGAYSINH,MALOP)
VALUES ('4','KHANH','2003-05-06','1')